---
title: "Лабораторная работа №1 по курсу «Машинное обучение»"
subtitle: "Тема: «Разведочный анализ данных. Подготовка и передача «живой» аналитики с помощью R Markdown»"
output: html_notebook
---

## 1. Цель лабораторной работы
-	Приобрести основные навыки работы с R пакетами для разведочного анализа данных
-	Освоить средства визуализации (диаграммы, графики и т.п.), чтобы сделать результаты анализа максимально доступными и понятными
- Освоить основные способы быстрого создания и передачи отчетов о результатах анализа данных 

## 2.Наборы данных лабораторной работы 1:

**2.1. Boston Housing:** 

[Boston Housing]() содержит данные, собранные Службой переписи населения США (англ. U.S Census Service), касающиеся недвижимости в районах Бостона. Набор данных состоит из 13 признаков и 506 строк и также предоставляет такую информацию, как уровень преступности (CRIM), ставка налога на недвижимость (TAX), возраст людей, которым принадлежит дом (AGE), соотношение числа учащихся и преподавателей в районе (PTRATIO) и другие. Данный набор данных используется для предсказания целевой переменой: средняя стоимость дома (MEDV).

**2.2. Pima Indians Diabetes Dataset ** 

[Pima Indians Diabetes Dataset]()

## 3. Задача:

**3.1. Загрузка данных из csv files**

**3.2. Изучение основных характеристик набора данных:**

- Размер датасета
- Список колнок с типами данных
- Проверка на наличие пропущенных значений (если в наборе данных имеются пропущенные значения -  требуется обработка этих пропущенных значений)
- Изучение основные статистических характеристик набора данных
- Определим эмпирическое среднее и дисперсию целевого признака
- ...

**3.3. Визуальное исследование набора данных (графики с использованием ggplot2):**

- Парные диаграммы
- Информация о корреляции признаков
- ...

**3.4. Создание отчетов с помощью Rmarkdown**

- Cоздать отчеты о проделанной в R работе с помощью **Rmarkdown**
- Конвертировать Rmarkdown в  документ Word и мне выслать 
- Конвертировать Rmarkdown в  html и опубликовать на бесплатном хостинке **Rpubs**. Мне выслать ссылку на опубликованные отчеты на **Rpubs**.


## Источники:

Руководство по Rmarkdown: https://bookdown.org/yihui/rmarkdown/

Визуализация данных с помощью R: https://rkabacoff.github.io/datavis/
